export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SINGUP_SUCCESS = "LOGIN_REQUEST";
export const SINGUP_REQUEST = "LOGIN_REQUEST";
export const SINGUP_FAILURE = "LOGIN_REQUEST";
